# Generated by Django 3.2.13 on 2022-11-11 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(default=0)),
                ('price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000000), django.core.validators.MinValueValidator(100)])),
            ],
        ),
    ]
