# Generated by Django 3.2.13 on 2022-11-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type_of_article',
        ),
    ]
