# Generated by Django 3.2.13 on 2022-11-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('articles', '0003_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.AddField(
            model_name='article',
            name='item',
            field=models.ManyToManyField(related_name='articles', to='items.Item'),
        ),
    ]
