# Generated by Django 3.2.13 on 2022-11-14 01:44

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
