# Generated by Django 3.2.13 on 2022-11-14 02:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='item',
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
