# Generated by Django 3.2.13 on 2022-11-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20221114_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
