# Generated by Django 3.2.12 on 2022-10-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='mola', max_length=20),
            preserve_default=False,
        ),
    ]
