# Generated by Django 3.2.12 on 2022-10-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_of_article',
            field=models.CharField(default='리뷰', max_length=20),
            preserve_default=False,
        ),
    ]
